import { RequestCookie } from "next/dist/compiled/@edge-runtime/cookies";
import Providers from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  cookies,
}: {
  children: React.ReactNode;
  cookies: RequestCookie[];
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers cookies={cookies}>{children}</Providers>
      </body>
    </html>
  );
}
